### ISSUE TITLE
Change NoSchedule taint to NoExecute to allow graceful termination/migration of pods during scale-down

### ISSUE THREAD

**Issue by christorpelund** [atlassian/escalator#142]
We've been testing escalator on a Kubernetes cluster with Istio and noticed that the NoSchedule taint during down-scaling does not attempt to gracefully terminate/migrate pods. This causes the Kubernetes cluster to become unreachable after terminating nodes with these critical pods. We can create a separate node group for auto-scaling non-critical pods but it's desirable to still have graceful termination of pods.

We experimented by changing the taint type to _TaintEffectNoExecute_ in taint.go and we achieved graceful termination of the pod and migration onto another Kubernetes node without a taint.

We were wondering if the usage of _TaintEffectNoSchedule_ was on purpose? And if not, could we do a PR to change to the [NoExecute](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) taint?

**Comment by awprice** [comment]
Glad to hear that you've been testing Escalator!

As Escalator is designed for job based workloads, we chose `TaintEffectNoSchedule` instead of `TaintEffectNoExecute` to allow the jobs that were running on the node to finish before terminating the node. Jobs ideally shouldn't be interrupted/rescheduled somewhere else unless they have been designed to handle that behaviour.

I would definitely be open to a PR adding an option to the node group config to allow for selection of NoSchedule/NoExecute as the taint for each node group. The default would have to be the current behaviour of NoSchedule.

**Comment by Jacobious52** [comment]
Pull request for this approved here #146
