### ISSUE TITLE
Maximum Taints

### ISSUE THREAD

**Issue by pauloribeiro-hotmart** [atlassian/escalator#162]
Hi,

Is there a reason why you have `MaximumTaints = 10` in taint.go? 
This is overriding the `fast_node_removal_rate ` configuration if it is bigger than 10.

Thanks!

**Comment by awprice** [comment]
`MaximumTaints` was added so that there was an upper bound to how many nodes Escalator would taint so if there was a configuration issue or something wrong it wouldn't taint every node in the node group. We haven't really experienced this happening though.

To be honest I think we should just remove the hard coded limit and let `fast_node_removal_rate` be the upper bound.

WDYT @Jacobious52 @dadux?

**Comment by Jacobious52** [comment]
Yup I agree, that should be removed. Was used as a reasonable number to avoid catastrophe errors before escalator was properly battle tested. It is now just extra complexity and clutter that isn't needed. We should entirely remove that hardcoded max limit code path and rely on `fast_node_removal_rate` implicitly.

**Comment by Jacobious52** [comment]
@pauloribeiro-hotmart This should be released now in `atlassian/escalator:v1.7.1` The `MaximumTaints` guard has been completely removed, so `fast_node_removal_rate` is now respected as the maximum taint amount. Please open an issue if there's any problems. Cheers.

**Comment by pauloribeiro-hotmart** [comment]
Thanks for the fast fix @Jacobious52 ! Really appreciate
